[package]
name = "apex-legends-simple-glow"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "winnt", "winbase","memoryapi"] }
lazy_static = "1.4.0"
windows = "0.43.0"
[lib]
crate-type = ["cdylib"]
name = "utility"
path = "src/utility.rs"